# This file defines the services that will be deployed to Render (https://render.com/)

services:
  # User and password not specified, so Render will generate them and they are not exposed in this repository
  - name: database
    type: pserv
    plan: free
    startCommand: ""  # Required but left empty

  - name: backend
    type: web
    runtime: node
    plan: free
    buildCommand: |
      npm install
      npm run build:dtos
      cd apps/backend
      npx prisma migrate deploy
      npm run build
    startCommand: cd apps/backend && npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false  # Set manually in Render Dashboard
      - key: JWT_SECRET
        sync: false  # Set manually in Render Dashboard
      - key: BUGSNAG_API_KEY
        sync: false  # Set manually in Render Dashboard

  - name: frontend
    type: web
    runtime: static
    plan: free
    buildCommand: |
      npm install
      npm run build:dtos
      cd apps/frontend
      npm run build
    staticPublishPath: apps/frontend/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false  # Set manually in Render Dashboard

  - name: landing
    type: web
    runtime: static
    plan: free
    buildCommand: |
      npm install
      cd apps/landing
      npm run build
    staticPublishPath: apps/landing/out
    envVars:
      - key: NEXT_PUBLIC_APP_URL
        sync: false  # Set manually in Render Dashboard

# Note: all secrets are defined on the Render dashboard to avoid storing them in the repository.
