# This file defines the services that will be deployed to Render (https://render.com/)

services:
  # User and password not specified, so Render will generate them and they are not exposed in this repository
  - name: database
    type: pserv
    plan: free

  - name: backend
    type: web
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build:dtos
      cd apps/backend
      npx prisma migrate deploy
      npm run build
    startCommand: cd apps/backend && npm run start:prod
    # Manually set this in Render's Dashboard
    envVars:
      - key: DATABASE_URL
      - key: JWT_SECRET
      - key: BUGSNAG_API_KEY

  - name: frontend
    type: web
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build:dtos
      cd apps/frontend
      npm run build
    staticPublishPath: apps/frontend/build
    # Manually set this in Render's Dashboard
    envVars:
      - key: REACT_APP_API_URL

  - name: landing
    type: web
    env: node
    plan: free
    buildCommand: |
      npm install
      cd apps/landing
      npm run build
    staticPublishPath: apps/landing/out
    # Manually set this in Render's Dashboard
    envVars:
      - key: NEXT_PUBLIC_APP_URL

# Note: all secrets are defined on the Render dashboard to avoid storing them in the repository.
