name: Backend CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build DTOs
        run: npm run build:dtos

      - name: Set env variables
        run: cd apps/backend && cp .env.test.example .env

      - name: Run Migrations
        run: cd apps/backend && npx prisma generate && npx prisma migrate deploy

      - name: Run Backend E2E test
        run: npm run test:e2e --workspace=apps/backend

      - name: Run Jest tests and check coverage
        run: npm run test:cov --workspace=apps/backend
