name: Playwright E2E Tests

on:
  push:
    branches:
      - main
  pull_request: # Not quite correct to run on production for PRs, should be in separate test env in real-world scenario

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: cd e2e && npm install

      - name: Install Playwright browsers
        run: cd e2e && npx playwright install --with-deps

      - name: Run Playwright tests
        run: cd e2e && npm run test:e2e
