name: Keep Render Awake
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
jobs:
  curl-api:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl -s https://backend-u7jt.onrender.com/api/v1/health
